version: '3.2'

services:

  tomcat:
    build:
      context: ./tomcat
    container_name: app
    ports:
        - "8080:8080"
    volumes:
        - "./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro"
        - "./tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml:ro"
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    environment:
        SERVICE_NAME: app
    networks:
        app_net:
          ipv4_address: 172.16.200.12
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
        - "./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf"
        - "./nginx/sites-available/gl.hf.conf:/etc/nginx/conf.d/gl.hf.conf:ro"
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    depends_on:
        - tomcat
    ports:
        - "127.0.0.1:80:80"
    links:
        - "tomcat"
    networks:
        app_net:
          ipv4_address: 172.16.200.11
    restart: always

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24

